import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title = process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || "MiniKit App";
  const description = process.env.NEXT_PUBLIC_APP_DESCRIPTION || 
    "Generated by `create-onchain --mini`, a Next.js template for MiniKit";
  const URL = process.env.NEXT_PUBLIC_URL;
  const heroImage = process.env.NEXT_PUBLIC_APP_HERO_IMAGE;
  const splashImage = process.env.NEXT_PUBLIC_APP_SPLASH_IMAGE;
  const splashBackground = process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR;
  const subtitle = process.env.NEXT_PUBLIC_APP_SUBTITLE;
  const tagline = process.env.NEXT_PUBLIC_APP_TAGLINE;

  return (
    <html lang="en">
      <head>
        <title>{title}</title>
        <meta name="description" content={description} />

        {/* ✅ Warpcast Frame Meta Tags */}
        <meta property="fc:frame" content="vNext" />
        <meta property="fc:frame:image" content={heroImage || ""} />
        <meta property="fc:frame:button:1" content={`Launch ${title}`} />
        <meta property="fc:frame:button:1:action" content="post" />
        
        {/* Mini-app specific configuration */}
        <meta property="fc:frame:post_url" content={URL || ""} />
        <meta property="fc:frame:button:1:target" content="launch_frame" />
        <meta property="fc:frame:button:1:launch_frame:url" content={URL || ""} />
        <meta property="fc:frame:button:1:launch_frame:name" content={title} />
        <meta property="fc:frame:button:1:launch_frame:splash_image" content={splashImage || ""} />
        <meta property="fc:frame:button:1:launch_frame:background" content={splashBackground || "#FFFFFF"} />
        
        {/* Optional metadata */}
        {subtitle && <meta property="fc:frame:subtitle" content={subtitle} />}
        {tagline && <meta property="fc:frame:tagline" content={tagline} />}
        
        {/* Open Graph tags for better sharing */}
        <meta property="og:title" content={process.env.NEXT_PUBLIC_APP_OG_TITLE || title} />
        <meta property="og:description" content={process.env.NEXT_PUBLIC_APP_OG_DESCRIPTION || description} />
        <meta property="og:image" content={process.env.NEXT_PUBLIC_APP_OG_IMAGE || heroImage || ""} />
      </head>
      <body className="bg-[#1a1a1a]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}