import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title = process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || "MiniKit App";
  const description =
    "Generated by `create-onchain --mini`, a Next.js template for MiniKit";
  const URL = process.env.NEXT_PUBLIC_URL;
  const heroImage = process.env.NEXT_PUBLIC_APP_HERO_IMAGE;
  const splashImage = process.env.NEXT_PUBLIC_SPLASH_IMAGE;
  const splashBackground = process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR;

  return (
    <html lang="en">
      <head>
        <title>{title}</title>
        <meta name="description" content={description} />

        {/* ✅ Warpcast Frame Meta Tags */}
        <meta property="fc:frame" content="vNext" />
        <meta property="fc:frame:image" content={heroImage || ""} />
        <meta property="fc:frame:button:1" content={`Launch ${title}`} />
        <meta property="fc:frame:post_url" content={URL || ""} />
        <meta property="fc:frame:splash:image" content={splashImage || ""} />
        <meta property="fc:frame:splash:background" content={splashBackground || "#FFFFFF"} />
      </head>
      <body className="bg-background">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
